= Coordinator election

== General Information

Generally speaking, the election of a new coordinator rigidly follows the algorithm described in the #link("https://didatticaonline.unitn.it/dol/pluginfile.php/2046075/mod_folder/content/0/ds1_project_2026_v3.20260625.pdf?forcedownload=1")[Project Document], election as the new leader the one that has the highest timestamp in the current epoch or the highest id in case of two replica having the same timestamp: when a replica does not receive the heartbeat message in the specified amount of time, fixed at 1 second, plus the maximum latency accounted for tolerance, it will setup itself to send an election message, triggering the leader election.

However, to limit the number of election messages circulating during a coordinator election, every replica waits a random time between the minimum and maximum latency multiplied by the total number of replicas: if after this period of time the replica is not in the election in progress status (registered by the attribute `hasElectionStarted`), it will proceed with sending a new election message to the next replica. This does not absolutely prevent the possibility of having multiple election messages but the system has been built by keeping in mind the possibility that, at worst, each replica will send an election message: specifically, the election message contains the replica who originally generated the election message (`originalReplicaId`), the map `<Integer, Integer>` of replicas who already received the message (`previousReplicasMap`) and the crashed coordinator for which the election was started (`crashedCoordinatorId`). \
Each replica has then two map, the first one, `electionRetriesMap`, contains, for each encountered `originalReplicaId`, the number of attempts that the replica performed to send the election message: this value is used as an offset to decide who is the next replica the current replica will try to contact to send the election message. Using a single `Integer` value to store this offset could cause concurrency-related problem since two different election message could arrive at the same time: if the next replica is crashed, the offset will be incremented by two instead of one. \
The second map, `receivedElectionAckMap`, keeps track, for each `originalReplicaId`, how many acknowledgements were received: this allows to avoid the same problem just described for the offset.

Even if multiple election messages are circulating the ring, this does not mean they will survive: upon receiving an election message, each replica check:
- if the id of said replica matches the one of the current coordinator. This can happen if the current replica is the current new coordinator, therefore, the received election message is no longer necessary;
- given the current message and its `previousReplicasMap`, the should-be leader is checked. If said coordinator is the one currently set as coordinator, meaning that the current replica received a synchronization message from the new coordinator, the election message is no longer useful and is therefore deleted from the ring;
- lastly, the `coordinatorSubstitutionMap`, a map that contains, for every crashed coordinator, its substitute. If the substitute for the `crashedCoordinatorId` is present in the map, the current election message is no longer needed and should be removed from the ring. This is useful if the new coordinator crash before sending the synchronization message, since it will remove any remaining election message that is still circulating the ring.

When a message should be removed from the ring, the acknowledgement message is still sent to the previous replica but with a boolean variable, `removedFromRing`, set as `true`: this will instruct the previous replica to also acknowledge that the election message was removed from the ring.

== Synchronization message

Every time a replica receives an election message, it automatically check for its presence in the `previousReplicasMap`: if thats the case, this means that the election message already traveled two times across the ring and the current replica has to decide if it is the right new coordinator. In such case, the replica first prepare the synchronization message, containing the database index, the database value and the timestamp of the latest stabilized write. The new coordinator next increment its epoch by 1 and reset the timestamp. Then, the coordinator update the map of replicas based on what was contained in the message that caused the replica to became the new coordinator and updates the quorum. Finally, the synchronization message is broadcasted to all still-alive replicas and previous unstable messages (including messages that arrived to the new coordinator from clients requesting a write) are sent to the coordinator itself in order for them to be correctly processed. At this time, the current coordinator id and the `coordinatorSubstitutionMap` are also updated, and heartbeat are resumed.

Upon receiving a synchronization message, each replica update the `coordinatorSubstitutionMap` and then check if their timestamp is lower that the timestamp contained in the synchronization message. This translates into the fact that the current replica is not updated with the latest write and should therefore update it internal database (this will also send the write result to the client who requested the write since the synchronization message also contains the id of the replica who requested that write). The replica then proceed to increment the epoch, reset the timestamp and resume the heartbeat listening process. Finally, like the newly elected coordinator, it also sends all unstable writes in order for them to be processed.

== Examined blocking situation and solutions

// in case of election started notice that even if some messages of the old election remain, thw il never reach the coordinator that now is offline, so no one will believe to be the leader based on that message: it will keep circulating until it will be removed because of the coordinatorSubstitutionMap