= Coordinator election

== General Information

Generally speaking, the election of a new coordinator rigidly follows the algorithm described in the #link("https://didatticaonline.unitn.it/dol/pluginfile.php/2046075/mod_folder/content/0/ds1_project_2026_v3.20260625.pdf?forcedownload=1")[Project Document], election as the new leader the one that has the highest timestamp in the current epoch or the highest id in case of two replica having the same timestamp: when a replica does not receive the heartbeat message in the specified amount of time, fixed at 1 second, plus the maximum latency accounted for tolerance, it will setup itself to send an election message, triggering the leader election.

However, to limit the number of election messages circulating during a coordinator election, every replica waits a random time between the minimum and maximum latency multiplied by the total number of replicas: if after this period of time the replica is not in the election in progress status (registered by the attribute `hasElectionStarted`), it will proceed with sending a new election message to the next replica. This does not absolutely prevent the possibility of having multiple election messages but the system has been built by keeping in mind the possibility that, at worst, each replica will send an election message: specifically, the election message contains the replica who originally generated the election message (`originalReplicaId`), the map `<Integer, Integer>` of replicas who already received the message (`previousReplicasMap`) and the crashed coordinator for which the election was started (`crashedCoordinatorId`). \
Each replica has then two maps, the first one, `electionRetriesMap`, contains, for each encountered `originalReplicaId`, the number of attempts that the replica performed to send the election message: this value is used as an offset to decide who is the next replica the current replica will try to contact to send the election message. Using a single `Integer` value to store this offset could cause concurrency-related problems since two different election messages could arrive at the same time: if the next replica is crashed, the offset will be incremented by two instead of one. \
The second map, `receivedElectionAckMap`, keeps track, for each `originalReplicaId`, of how many acknowledgments were received: this allows to avoid the same problem just described for the offset.

Even if multiple election messages are circulating the ring, this does not mean they will survive: upon receiving an election message, each replica checks:
- if the id of said replica matches the one of the current coordinator. This can happen if the current replica is the current new coordinator, therefore, the received election message is no longer necessary;
- given the current message and its `previousReplicasMap`, the should-be leader is checked. If said coordinator is the one currently set as coordinator, meaning that the current replica received a synchronization message from the new coordinator, the election message is no longer useful and is therefore deleted from the ring;
- lastly, the `coordinatorSubstitutionMap`, a map that contains, for every crashed coordinator, its substitute. If the substitute for the `crashedCoordinatorId` is present in the map, the current election message is no longer needed and should be removed from the ring. This is useful if the new coordinator crashes before sending the synchronization message, since it will remove any remaining election message that is still circulating the ring.

When a message should be removed from the ring, the acknowledgment message is still sent to the previous replica but with a boolean variable, `removedFromRing`, set as `true`: this will instruct the previous replica to also acknowledge that the election message was removed from the ring.

Finally, while `previousReplicasMap` is sent as a `Collections` unmodifiable map, this does not necessarily mean that the list will always stay the same: it may happen that a replica crashes after receiving an election message for the first time: in such case, the replica that was waiting for an acknowledgement from such replica will remove the crashed replica from the map, preventing any replica from considering the crashed replica as a possible new coordinator.

== Synchronization message

Every time a replica receives an election message, it automatically checks for its presence in the `previousReplicasMap`: if that is the case, this means that the election message already traveled two times across the ring and the current replica has to decide if it is the right new coordinator. In such case, the replica first prepares the synchronization message, containing the database index, the database value and the timestamp of the latest stabilized write. The new coordinator next increments its epoch by 1 and reset the timestamp. Then, the coordinator will update the map of replicas based on what was contained in the message that caused the replica to become the new coordinator and updates the quorum. Finally, the synchronization message is broadcasted to all still-alive replicas and previous unstable messages (including messages that arrived to the new coordinator from clients requesting a write) are sent to the coordinator itself in order for them to be correctly processed. At this time, the current coordinator id and the `coordinatorSubstitutionMap` are also updated, and heartbeats are resumed.

Upon receiving a synchronization message, each replica updates the `coordinatorSubstitutionMap` and then checks if their timestamp is lower than the timestamp contained in the synchronization message. This translates into the fact that the current replica is not updated with the latest write and should therefore update its internal database (this will also send the write result to the client who requested the write since the synchronization message also contains the id of the replica who requested that write). The replica then proceeds to increment the epoch, reset the timestamp and resume the heartbeat listening process. Finally, like the newly elected coordinator, the replica also sends all unstable writes in order for them to be processed.

== Examined blocking situation and solutions

// in case of election started notice that even if some messages of the old election remain, thw il never reach the coordinator that now is offline, so no one will believe to be the leader based on that message: it will keep circulating until it will be removed because of the coordinatorSubstitutionMap

When an election is in progress, a crash can still happen: for this reason, various cases have been taken into consideration.

Firstly, as was previously discussed, if a replica was in the `previousReplicasMap` but it did not acknowledge an election message, the replica is removed from the `previousReplicasMap`: the previous replica, however, also checks if, given the new list, it needs to be the new leader. Therefore, this covers the case of a to-be coordinator that crashes before sending the acknowledgment message to the previous replica.

Another possible crash may happen when the to-be coordinator acknowledges the election message, but it crashes before sending a synchronization message. To cover this situation, when an election starts, every replica automatically schedule a check to understand whether the election ended (in other words, a synchronization message was received) within a certain period of time (see the next section).

In case the synchronization message is not received in time, the replica will reset the status of the election and then it will send a newly generated election message for the same crashed coordinator as before. Notice that in this situation two election messages are circulating: the one for the crashed to-be coordinator and the one for the new election. However, since the old to-be coordinator is now crashed, it will not be able to receive the message that should cause the election to end and every replica will automatically delete all remaining election messages when a new coordinator is elected, since this will cause the `coordinatorSubstitutionMap` to be populated, causing the various replicas to not consider (and removing) the remaining election messages.

== Chosen timeouts

For the coordinator election the following timeouts have been set:
- the coordinator sends a heartbeat in broadcast every second; // coordinator beat interval
- a replica checks if a heartbeat was received every second plus the maximum latency (plus tolerance) to cover for network latency; // get heartbeat received check time
- when a replica detects a missing heartbeat, a random time (numbers of actors multiplied by a random number between the minimum and maximum latency) is waited to prevent multiple election messages circulating through the ring; // new election message wait time
- a replica waits for an acknowledgment for an election message the maximum latency (with tolerance) multiplied by two to cover the round trip time plus additional time to cover for messages processing time (50 ms for every replica, since in the worst case everyone generated an election message); // Election ack wait time
- a replica waits for the final synchronization message from the new coordinator for 5 seconds (to cover messages processing time by the various replicas and the time needed to receive the synchronization message) plus the time needed for an election message to circulating two times the ring at worst case (therefore, the maximum latency multiplied by the number of replicas multiplied by 2 to cover the "double walk") plus the time to cover for the 2 acknowledgment (therefore, the election message acknowledgment wait time, multiplied by two). // sync message wait time

